name:                budget
version:             0.1.0.0
github:              "githubuser/budget"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/budget#readme>

extra-deps:
- git: git@github.com:bitemyapp/esqueleto.git
  commit: b81e0d951e510ebffca03c5a58658ad884cc6fbd
  name: esqueleto

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- text
- persistent
- persistent-template
- persistent-postgresql
- monad-logger
- transformers
- resourcet
- unliftio-core
- time

library:
  source-dirs: src

executables:
  budget-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - budget

tests:
  budget-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - budget
